export const GET_POSTS = "GET_POSTS";
export const GET_POSTS_PENDING = "GET_POSTS_PENDING";
export const GET_POSTS_FULFILLED = "GET_POSTS_FULFILLED";
export const GET_POSTS_REJECTED = "GET_POSTS_REJECTED";

export const CREATE_POST = "CREATE_POST";
export const CREATE_POST_PENDING = "CREATE_POST_PENDING";
export const CREATE_POST_FULFILLED = "CREATE_POST_FULFILLED";
export const CREATE_POST_REJECTED = "CREATE_POST_REJECTED";
