export const GET_POSTS = "GET_POSTS";
export const GET_POSTS_PENDING = "GET_POSTS_PENDING";
export const GET_POSTS_FULFILLED = "GET_POSTS_FULFILLED";
export const GET_POSTS_REJECTED = "GET_POSTS_REJECTED";

export const CREATE_POST = "CREATE_POST";
export const CREATE_POST_PENDING = "CREATE_POST_PENDING";
export const CREATE_POST_FULFILLED = "CREATE_POST_FULFILLED";
export const CREATE_POST_REJECTED = "CREATE_POST_REJECTED";

export const GET_COMMENTS = "GET_COMMENTS";
export const GET_COMMENTS_PENDING = "GET_COMMENTS_PENDING";
export const GET_COMMENTS_FULFILLED = "GET_COMMENTS_FULFILLED";
export const GET_COMMENTS_REJECTED = "GET_COMMENTS_REJECTED";
